### ISSUE TITLE
关于闪退的问题

### ISSUE THREAD

**Issue by zty0510** [js-shi/E-140W-P_TelecomAdmin_Rel#2]
您好，我在win10 64位下  已从cmd运行软件，但是当输入好ip地址回车后，就闪退了！求解，谢谢

**Comment by js-shi** [comment]
如果是在cmd窗口下运行的话，即使闪退应该cmd窗口还留着的吧？有没有报错信息，截个图看一下。

**Comment by ienvyyou** [comment]
大佬。。我也碰到楼主的问题。。我也是WIN10 64的。。打开输入ip就跳，也没报错也没窗口。。完全消失了，用兼容模式也是一样。。。

**Comment by ienvyyou** [comment]
> 如果是在cmd窗口下运行的话，即使闪退应该cmd窗口还留着的吧？有没有报错信息，截个图看一下。
大佬。。我也碰到楼主的问题。。我也是WIN10 64的。。打开输入ip就跳，也没报错也没窗口。。完全消失了，用兼容模式也是一样。。。

**Comment by zty0510** [comment]
解决了，知道问题出在哪了，自己的问题，打扰了 ，谢谢！

**Comment by js-shi** [comment]
> 
> 
> 大佬。。我也碰到楼主的问题。。我也是WIN10 64的。。打开输入ip就跳，也没报错也没窗口。。完全消失了，用兼容模式也是一样。。。

听上去你是双击运行的啊……确定你是在cmd窗口里输入exe的名字启动的么？
